spring :
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/news?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

